deploy:
  needs: build
  runs-on: ubuntu-latest
  
  steps:
  - name: Checkout Repository
    uses: actions/checkout@v2
    
  - name: Install Dependencies
    run: npm install
    
  - name: Deploy to Render
    run: |
      # Install the Render CLI
      curl -sL https://render.com/install.sh | sh
      
      # Deploy the application to Render (replace 'your-render-service-name' with the name of your Render service)
      render deploy --branch main --name blog-deploy
